name: Build

on: 
  push:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
      
    steps:
    - uses: actions/checkout@v3
      
    - name: "Install prerequisites"
      run: |
        sudo make prepare
      
    - name: "Build"
      run: |
        sudo make build